// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5UINT5W2CS4Gl-SXfFNR5Y-7XVtBGreQ',
    appId: '1:863498003612:web:2dd5a3ae3af1bb7d1c3959',
    messagingSenderId: '863498003612',
    projectId: 'mwcoffee-eafe0',
    authDomain: 'mwcoffee-eafe0.firebaseapp.com',
    storageBucket: 'mwcoffee-eafe0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIAhreyESiz9-yi-Zf4-a_sw2yxX6OUqQ',
    appId: '1:863498003612:android:ed42fd78d8acec651c3959',
    messagingSenderId: '863498003612',
    projectId: 'mwcoffee-eafe0',
    storageBucket: 'mwcoffee-eafe0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxb5QIAlhBpDSFluFczLdIBQuct950BYg',
    appId: '1:863498003612:ios:689024db0255bc8a1c3959',
    messagingSenderId: '863498003612',
    projectId: 'mwcoffee-eafe0',
    storageBucket: 'mwcoffee-eafe0.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxb5QIAlhBpDSFluFczLdIBQuct950BYg',
    appId: '1:863498003612:ios:689024db0255bc8a1c3959',
    messagingSenderId: '863498003612',
    projectId: 'mwcoffee-eafe0',
    storageBucket: 'mwcoffee-eafe0.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5UINT5W2CS4Gl-SXfFNR5Y-7XVtBGreQ',
    appId: '1:863498003612:web:1b6bf1c24c3ad64e1c3959',
    messagingSenderId: '863498003612',
    projectId: 'mwcoffee-eafe0',
    authDomain: 'mwcoffee-eafe0.firebaseapp.com',
    storageBucket: 'mwcoffee-eafe0.firebasestorage.app',
  );
}
